### PR TITLE
Changes for landing https://github.com/dart-lang/sdk/issues/32161

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
Add void declarations to methods with implicit dynamic returning void
values, which may be illegal in dart 2, but in either case, expresses
the current intent better.

### CODE REVIEW

**Comment by nshahan** [comment]
Thanks! Can you update the pubspec version to 0.21.0+1-dev and add an entry to the CHANGELOG? Now that the two repos are in sync I want to track changes carefully.

**Comment by MichaelRFairhurst** [comment]
Done! Apologies for the delay.

**Review by nshahan — APPROVED** [review]
LGTM Thanks!

**Comment by MichaelRFairhurst** [comment]
I'm going to pull this into g3 -- did you want to do a publish first or are you OK with pulling in the latest hash?

**Pull request merged**
