### PR TITLE
Allow dart_internal 0.2.0 & fix analyzer/formatter issues

### PR DESCRIPTION
**Pull request by lukaszkolodziejczyk**

### CODE REVIEW

**Comment by lukaszkolodziejczyk** [comment]
@kevmoo

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
I'm not sure who owns this, sadly. Need to dig.

**Comment by kevmoo** [comment]
@nshahan – do you have admin access here?

**Comment by nshahan** [comment]
No, I do not.

**Comment by kevmoo** [comment]
@mit-mit – can you give me keys here?

**Comment by mit-mit** [comment]
Invite sent

**Comment by markegli** [comment]
Sorry I was slow on this. Thanks everyone for covering.

**Pull request merged**
