### PR TITLE
Add listObserved and listUnobserved callbacks

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by dotdoom** [comment]
A friendly ping for code owner @matanlurey!
+cc @davidmorgan.

**Comment by dotdoom** [comment]
Feeling lonely in this PR, @matanlurey , @davidmorgan can you give me a clue?

**Comment by davidmorgan** [comment]
I'm not really sure the status of this package ... maybe @kevmoo @nshahan

**Comment by nshahan** [comment]
What use case/problem is this trying to solve? It feels like this might be for an application specific use case since it doesn't include similar functionality for the observable maps. 

I'm reluctant to increase the size of the API without a strong justification.

**Comment by dotdoom** [comment]
@nshahan thanks for taking a look.

Some context on the problem this is trying to solve is in #78 (last point). Specifically, this would allow the list to dynamically populate *only* when there's at least one subscriber (to reduce the waste of resources when fetching from e.g. a remote database).

There's also a TODO comment that suggests that a similar interface was in plans:
https://github.com/dart-lang/observable/blob/04eae7a581f585fc9bafa9a36d2817e14c19c5aa/lib/src/observable_list.dart#L112-L114

Lastly, I don't see how this can be implemented for observable maps which do not have anything analogical to `_listChanges`. Let me know what you mean by similar functionality for maps and I'm happy to update this PR!

**Comment by dotdoom** [comment]
One alternative approach that I could try to implement is sending a notification (via `notifyPropertyChange`) that `hasListObservers` has changed.

https://github.com/dart-lang/observable/blob/04eae7a581f585fc9bafa9a36d2817e14c19c5aa/lib/src/observable_list.dart#L123-L125

I.e. something along these lines:

```diff
  _listChanges = new StreamController.broadcast(
    sync: true,
+   onListen: () => notifyPropertyChange(#hasListObservers, false, true),
    onCancel: () {
      _listChanges = null;
+     notifyPropertyChange(#hasListObservers, true, false);
    },
```

WDYT?

**Comment by matanlurey** [comment]
From my perspective, this package no longer offers anything that generally useful (the concept of observe-ability of collections stock has gone down quite a bit with the rise of immutability). I wouldn't want to add anything else to the API surface going forward.

**Comment by dotdoom** [comment]
@matanlurey thank you for your comment. I risk making a very specific example, but on a bright side it's realistic: I'd appreciate a hint on how list animations, in response to item addition / removal, can be implemented with immutable collections. Specifically the logic of detecting which items are inserted, removed or moved.

**Comment by matanlurey** [comment]
Unfortunately I am not prepared to do code reviews or advice here. StackOverflow is a better option.

**Comment by dotdoom** [comment]
@matanlurey okay.  I must have misunderstood the purpose your statement about this package no longer providing anything generally useful.

**Comment by dotdoom** [comment]
@nshahan, @matanlurey  can I get your comment on the solution I proposed [above](https://github.com/dart-lang/observable/pull/79#issuecomment-489745604)?

Sorry but I'm not buying an argument that "this package no longer offers anything that generally useful" and therefore "wouldn't want to add anything else to the API surface". This doesn't sound reasonable from an engineering perspective, given that I am offering to merge a PR with documentation and full coverage by tests (and if you disagree, I am happy to add more).

Even if UI moves forward to the world of immutable collections, which I appreciate, solutions like Firebase Database and Firestore operate on a concept of events modifying existing collections, not sending the whole dataset over and over.

**Comment by dotdoom** [comment]
@nshahan, @matanlurey -- a firndly ping.

**Comment by dotdoom** [comment]
@nshahan , @matanlurey -- a not so friendly friendly ping.

**Comment by dotdoom** [comment]
Socially awkward ping?

**Comment by nshahan** [comment]
> Sorry but I'm not buying an argument that "this package no longer offers anything that generally useful" and therefore "wouldn't want to add anything else to the API surface". This doesn't sound reasonable from an engineering perspective, given that I am offering to merge a PR with documentation and full coverage by tests (and if you disagree, I am happy to add more).

@dotdoom I appreciate your effort here and adding documentation and tests are helpful. 😄There are more engineering costs we have to consider though. Any new API needs to be evaluated in the design patterns of large applications and frameworks where the package is already or could be used in the future. 

Once the new API is added and it gains uses there could be unintended consequences and cleaning it up later could be difficult and time consuming. For example, how does the API interact with Angular change detection and the component life cycle? Does it conflict with changes the Angular team might be wanting to make already? How does it interact with apps built in Flutter and its roadmap? I'm not asking for you to answer these questions, just posing them as hypothetical issues that could require additional design work and evaluation.

We currently don't have any of these evaluations planned for this package and can't justify adding more to the API without that type of work. I'm going to close the pull request for now, but we can refer back to this in the future if there is a proven use case that requires these types of changes and they are fully evaluated.

**Pull request closed without merging**
